# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.TextField(choices=[('undefined', 'undefined'), ('strategy', 'strategy'), ('shooting', 'shooting'), ('arcade', 'arcade'), ('adventure', 'adventure')], default='undefined'),
        ),
    ]
