# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0002_auto_20170119_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='game_thumbnails'),
        ),
    ]
