# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0003_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
