# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 14:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password

def add_initial_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    SiteUser = apps.get_model("gamehost", "SiteUser")
    db_alias = schema_editor.connection.alias
    user = User.objects.using(db_alias).create(username="user", password=make_password("user"))
    SiteUser.objects.using(db_alias).create(user=user)
    dev = User.objects.using(db_alias).create(username="dev", password=make_password("dev"))
    SiteUser.objects.using(db_alias).create(user=dev, developer_status=True)
    admin = User.objects.using(db_alias).create(username="admin", password=make_password("admin"),
                                                is_superuser=True, is_staff=True)
    SiteUser.objects.using(db_alias).create(user=admin, developer_status=True)

def remove_initial_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(username="user").delete()
    User.objects.using(db_alias).filter(username="dev").delete()
    User.objects.using(db_alias).filter(username="admin").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0004_auto_20170123_1204'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]
