# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gamehost.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0005_add_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('in_progress', 'in_progress'), ('success', 'success')], default='in_progress')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(default=gamehost.models.default_payment, on_delete=django.db.models.deletion.CASCADE, to='gamehost.Payment'),
        ),
    ]
