# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-13 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0006_auto_20170213_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 2, 13, 14, 21, 52, 91746, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
