# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-13 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehost', '0007_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='category',
            new_name='status',
        ),
    ]
